import type { PrismaClient } from "../../generated/prisma/client";
import { homePageSeed } from "../seed-data";
import { toJson } from "./helpers";

export async function seedHomePage(
  prisma: PrismaClient,
  assetIds: { homeOgId: number },
): Promise<number> {
  await prisma.homePage.upsert({
    where: { id: 1 },
    update: {
      aboutMissionBody: homePageSeed.aboutMissionBody,
      aboutMissionTitle: homePageSeed.aboutMissionTitle,
      aboutSummaryCtaLabel: homePageSeed.aboutSummaryCtaLabel,
      aboutSummaryCtaUrl: homePageSeed.aboutSummaryCtaUrl,
      aboutSummarySubtitle: homePageSeed.aboutSummarySubtitle,
      aboutSummaryTitle: homePageSeed.aboutSummaryTitle,
      aboutWhyChoosePoints: toJson(homePageSeed.aboutWhyChoosePoints),
      aboutWhyChooseTitle: homePageSeed.aboutWhyChooseTitle,
      contactCtaActions: toJson(homePageSeed.contactCtaActions),
      contactCtaBody: homePageSeed.contactCtaBody,
      contactCtaTitle: homePageSeed.contactCtaTitle,
      customSolutionsCtaLabel: homePageSeed.customSolutionsCtaLabel,
      customSolutionsCtaUrl: homePageSeed.customSolutionsCtaUrl,
      customSolutionsDevelopmentBody: homePageSeed.customSolutionsDevelopmentBody,
      customSolutionsDevelopmentTitle: homePageSeed.customSolutionsDevelopmentTitle,
      customSolutionsFeatures: toJson(homePageSeed.customSolutionsFeatures),
      customSolutionsProcessSteps: toJson(homePageSeed.customSolutionsProcessSteps),
      customSolutionsProcessTitle: homePageSeed.customSolutionsProcessTitle,
      customSolutionsSubtitle: homePageSeed.customSolutionsSubtitle,
      customSolutionsTitle: homePageSeed.customSolutionsTitle,
      heroEyebrow: homePageSeed.heroEyebrow,
      heroHeading: homePageSeed.heroHeading,
      heroPrimaryCtaLabel: homePageSeed.heroPrimaryCtaLabel,
      heroPrimaryCtaUrl: homePageSeed.heroPrimaryCtaUrl,
      heroSecondaryCtaLabel: homePageSeed.heroSecondaryCtaLabel,
      heroSecondaryCtaUrl: homePageSeed.heroSecondaryCtaUrl,
      heroStats: toJson(homePageSeed.heroStats),
      heroSubheading: homePageSeed.heroSubheading,
      heroVisualAssetId: assetIds.homeOgId,
      metaDescription: homePageSeed.metaDescription,
      metaTitle: homePageSeed.metaTitle,
      ogImageAssetId: assetIds.homeOgId,
      productsSectionIntro: homePageSeed.productsSectionIntro,
      productsSectionTitle: homePageSeed.productsSectionTitle,
      projectsSectionIntro: homePageSeed.projectsSectionIntro,
      projectsSectionTitle: homePageSeed.projectsSectionTitle,
      servicesSectionIntro: homePageSeed.servicesSectionIntro,
      servicesSectionTitle: homePageSeed.servicesSectionTitle,
      testimonialsSectionIntro: homePageSeed.testimonialsSectionIntro,
      testimonialsSectionTitle: homePageSeed.testimonialsSectionTitle,
    },
    create: {
      aboutMissionBody: homePageSeed.aboutMissionBody,
      aboutMissionTitle: homePageSeed.aboutMissionTitle,
      aboutSummaryCtaLabel: homePageSeed.aboutSummaryCtaLabel,
      aboutSummaryCtaUrl: homePageSeed.aboutSummaryCtaUrl,
      aboutSummarySubtitle: homePageSeed.aboutSummarySubtitle,
      aboutSummaryTitle: homePageSeed.aboutSummaryTitle,
      aboutWhyChoosePoints: toJson(homePageSeed.aboutWhyChoosePoints),
      aboutWhyChooseTitle: homePageSeed.aboutWhyChooseTitle,
      contactCtaActions: toJson(homePageSeed.contactCtaActions),
      contactCtaBody: homePageSeed.contactCtaBody,
      contactCtaTitle: homePageSeed.contactCtaTitle,
      customSolutionsCtaLabel: homePageSeed.customSolutionsCtaLabel,
      customSolutionsCtaUrl: homePageSeed.customSolutionsCtaUrl,
      customSolutionsDevelopmentBody: homePageSeed.customSolutionsDevelopmentBody,
      customSolutionsDevelopmentTitle: homePageSeed.customSolutionsDevelopmentTitle,
      customSolutionsFeatures: toJson(homePageSeed.customSolutionsFeatures),
      customSolutionsProcessSteps: toJson(homePageSeed.customSolutionsProcessSteps),
      customSolutionsProcessTitle: homePageSeed.customSolutionsProcessTitle,
      customSolutionsSubtitle: homePageSeed.customSolutionsSubtitle,
      customSolutionsTitle: homePageSeed.customSolutionsTitle,
      heroEyebrow: homePageSeed.heroEyebrow,
      heroHeading: homePageSeed.heroHeading,
      heroPrimaryCtaLabel: homePageSeed.heroPrimaryCtaLabel,
      heroPrimaryCtaUrl: homePageSeed.heroPrimaryCtaUrl,
      heroSecondaryCtaLabel: homePageSeed.heroSecondaryCtaLabel,
      heroSecondaryCtaUrl: homePageSeed.heroSecondaryCtaUrl,
      heroStats: toJson(homePageSeed.heroStats),
      heroSubheading: homePageSeed.heroSubheading,
      heroVisualAssetId: assetIds.homeOgId,
      id: 1,
      metaDescription: homePageSeed.metaDescription,
      metaTitle: homePageSeed.metaTitle,
      ogImageAssetId: assetIds.homeOgId,
      productsSectionIntro: homePageSeed.productsSectionIntro,
      productsSectionTitle: homePageSeed.productsSectionTitle,
      projectsSectionIntro: homePageSeed.projectsSectionIntro,
      projectsSectionTitle: homePageSeed.projectsSectionTitle,
      servicesSectionIntro: homePageSeed.servicesSectionIntro,
      servicesSectionTitle: homePageSeed.servicesSectionTitle,
      testimonialsSectionIntro: homePageSeed.testimonialsSectionIntro,
      testimonialsSectionTitle: homePageSeed.testimonialsSectionTitle,
    },
  });

  return 1;
}
